
#Here are configs that need reloading to take effect
[general]
	#Enable Creative Tab
	creative_tab = false
	#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
	dispensers = true
	#Creates a creative tab full of filled jars
	jar_tab = false
	#Enables custom Configured config screen
	custom_configured_screen = true
	#Save generated resources to disk in a 'debug' folder in your game directory. Mainly for debug purposes but can be used to generate assets in all wood types for your mods :0
	debug_save_dynamic_pack = false

[blocks]
	planter = true
	clock_block = true
	pedestal = true
	wind_vane = true
	redstone_illuminator = true
	notice_board = true
	crank = true
	jar = true
	faucet = true
	turn_table = true
	spring_launcher = true
	speaker_block = true
	sign_post = true
	hanging_sign = true
	bellows = false
	sconce = false
	sconce_green = false
	cage = true
	item_shelf = true
	sconce_lever = false
	cog_block = true
	globe = true
	hourglass = true
	sack = true
	blackboard = true
	safe = true
	copper_lantern = false
	gold_trapdoor = false
	gold_door = false
	bamboo_spikes = true
	bamboo_spikes_tipped = true
	stone_lamp = false
	end_stone_lamp = false
	blackstone_lamp = false
	deepslate_lamp = false
	checker_block = true
	netherite_door = false
	netherite_trapdoor = false
	lock_block = true
	flax = true
	rope = true
	pulley_block = true
	fodder = true
	crimson_lantern = true
	magma_cream_block = false
	daub = true
	wattle_and_daub = true
	timber_frame = true
	flag = true
	stone_tile = false
	goblet = true
	raked_gravel = true
	statue = true
	iron_gate = true
	feather_block = true
	flint_block = true
	urn = true
	ash = true
	ash_bricks = false
	doormat = true
	flower_box = true
	blackstone_tile = false
	globe_sepia = true
	present = true
	sugar_cube = false
	lapis_bricks = false
	relayer = true
	crystal_display = true
	candle_holder = false
	silver_trapdoor = false
	silver_door = false
	lead_trapdoor = false
	lead_door = false

[items]
	flute = true
	stasis = true
	dispenser_minecart = true
	soap = true
	bubble_blower = true
	antique_ink = true
	shulker_shell = true
	candy = true
	wrench = true
	slingshot = true
	rope_arrow = true
	bomb = true
	pancake = false
	quiver = true

